<?php

namespace app\common\controller;

use think\Controller;

/**
 * 前台控制器基类
 */
class Frontend extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }
}
